services:
  postgres:  # ВАЖНО: Название базы остаётся таким же, как в локальной разработке
    image: ghcr.io/stromwasser/messageexchangesolution-db:latest
    container_name: postgres
    restart: always
    networks:
      - app_network

  api:
    image: ghcr.io/stromwasser/messageexchangesolution-api:latest
    container_name: messageexchange_api
    depends_on:
      - postgres
    restart: always
    environment:
      ASPNETCORE_URLS: "http://+:7043"
      DB_CONNECTION_STRING: "Host=postgres;Port=5432;Database=MessageExchangeDB;Username=postgres;Password=postgres"
    ports:
      - "7043:7043"
    networks:
      - app_network

  client:
    image: ghcr.io/stromwasser/messageexchangesolution-client:latest
    container_name: messageexchange_client
    depends_on:
      - api
    restart: always
    ports:
      - "7080:80"
    networks:
      - app_network

networks:
  app_network:
